import Head from 'next/head'
import Banner from '../components/banner/banner.'




export default function Home() {
  return (
    <div >
      <Head>
        <title>NETFLIX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>

      <main>
        <Banner 
        title = "NETFLIX"
        subTitle="story of a neon girl..."
        imgUrl="/static/neongirl.jpg"/>
        
      </main>
    </div>
  )
}
